# Generated by Django 3.2.5 on 2022-06-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(help_text='Enter company name', max_length=200)),
                ('UEN', models.CharField(help_text='Enter UEN', max_length=200)),
                ('DOI', models.DateField(help_text='Enter date of incorporation')),
                ('emailaddress', models.EmailField(help_text='Enter email address', max_length=200)),
                ('password', models.CharField(help_text='Enter password)', max_length=200)),
                ('documents', models.CharField(help_text='Uploaded documents', max_length=200)),
                ('Hashkey', models.CharField(default='', help_text='ModelHash', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=200)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=200)),
                ('DOB', models.DateField(help_text='Enter date of birth')),
                ('emailaddress', models.EmailField(help_text='Enter email address', max_length=200)),
                ('password', models.CharField(help_text='Enter password)', max_length=200)),
                ('documents', models.CharField(help_text='Uploaded documents', max_length=200)),
                ('Hashkey', models.CharField(default='', help_text='ModelHash', max_length=200)),
            ],
        ),
    ]
