# Generated by Django 4.0.5 on 2022-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_rename_documents_profile_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Date',
            field=models.DateField(default='1900-01-01', help_text='Date of Birth/Incorporation'),
        ),
    ]
