# Generated by Django 3.2.5 on 2022-06-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Homepage', '0002_auto_20220613_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=200)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=200)),
                ('DOB', models.CharField(help_text='Enter date of birth', max_length=200)),
                ('emailaddress', models.CharField(help_text='Enter email address', max_length=200)),
                ('password', models.CharField(help_text='Enter password)', max_length=200)),
                ('documents', models.CharField(help_text='Uploaded documents', max_length=200)),
            ],
        ),
    ]
